title: Capítulo ACM PUC
description: > # this means to ignore newlines until "baseurl:"
  Página temporal del Capítulo ACM PUC
github_username: Hernan4444

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "assets"
    values:
      image: true
theme: jekyll-theme-minimal

# Poner nombre del tema,cantidad de imagenes
vida_universitaria:
  - DCCerro,5
  - Tarreo,12
  # - torneo-programacion,16

