title: Capítulo SIAM-PUC
description: > # this means to ignore newlines until "baseurl:"
  Material y presentación del Capítulo
github_username: capitulosiampuc

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "assets"
    values:
      image: true
theme: jekyll-theme-minimal

# Poner nombre del tema,cantidad de imagenes
#vida_universitaria:
  #- DCCerro,5
  #- Tarreo,12
  # - torneo-programacion,16

